### ISSUE TITLE
pretrained models 

### ISSUE THREAD

**Issue by ljc0815** [CNJianLiu/6D-CLGrasp#2]
Hello, I tried to download pretrained models but it was unsuccessful. Can you provide another copy of the pretrained models?

**Comment by CNJianLiu** [comment]
> Hello, I tried to download pretrained models but it was unsuccessful. Can you provide another copy of the pretrained models?

Hi, I have tried to download the pretrained models now, it is ok. I think you can check your network. Also, you can train the network, which is not difficult. Hope this helps :)
