### ISSUE TITLE
Hello,how to obtain point clouds

### ISSUE THREAD

**Issue by AFESDTTM** [CNJianLiu/6D-CLGrasp#3]
How to obtain the point cloud in your paper? Was it generated using code? If so, could you provide the code

![image](https://github.com/CNJianLiu/6D-CLGrasp/assets/106895081/08b5fb07-64d0-4e14-a6d8-f2bcde4d334a)

**Comment by CNJianLiu** [comment]
Hi, you can use this [function](https://github.com/CNJianLiu/6D-CLGrasp/blob/3e915a845d84057e9db8ea52d779149dee5ebabf/tools/visual_points.py#L25).

**Comment by AFESDTTM** [comment]
thank you.
